language: node_js
node_js:
  - '6.9.2'
  - '7.0.0'
  - '7.1.0'
  - '7.2.0'
  - '7.3.0'
sudo: false

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
